### ISSUE TITLE
Cannot start the app

### ISSUE THREAD

**Issue by FlorentD** [alexandreferreirafr/React-Redux-Movie-List#1]
Hey !

Why did you delete tools/ folder ? `npm start`command cannot run because of missing file `tools/startMessage.js`.

Is there another way to launch the app ?

**Comment by alexandreferreirafr** [comment]
My bad, I deleted by mistake. it should work now!

**Comment by alexandreferreirafr** [comment]
Je te laisse mon numéro si t'as besoin de me joindre : 06 75 33 95 33

**Comment by FlorentD** [comment]
Hello !

Merci beaucoup pour le temps qui tu as pris pour faire cette exercice ! L'interface est cool et ça fait le taff. 
- La partie React/Redux est plutôt bien implémentée
- Le CSS est top

Malgré ça, avec les équipes, on a finalement convenu de prendre quelqu'un avec un peu plus d'expérience en ReactJS/ES6 pour intégrer notre équipe, ça a été un choix difficile.

Voici en vrac quelques remarques sur le code qui on fait pencher la balance : 
- Le choix de prendre un bootstrap react est louable mais ça peut être un peu lourd, notamment si tu n'as pas l'intention d'écrire des tests. Laisser le `index.spec.js` fait un peu tâche :-)
- Idem pour le linter, c'est bien d'en avoir un mais si on ne l'utilise pas, ça alourdit le projet pour rien (Il y a 34 warnings sur le projet)
- Il aurait été mieux de cleaner les `console.log()` ainsi que les lignes mises en commentaires !
- `App` aurait dû être un pure component.
- Dans `MoviePage`, tu fais un `document.addEventListener('keydown', this.keyNavigation)` au mount. Le problème c'est que tu ne removes pas le `listener`quand tu unmout. Du coup quand tu vas sur une fiche et que tu reviens, tu as 2 eventListener. Ca provoque des bugs de navigation.
- Plus généralement, vouloir faire une navigation par clavier est très bien mais si elle n'est pas finie ou buggée, c'est décevant.

J'aurais préféré avoir quelque chose de plus simple mais de plus propre ! 

Voilà, j'espère que tu trouveras une autre mission très vite et on reste ouvert si dans quelques temps tu souhaites venir chez Canal !

A bientôt dans un meetup ou autre !

Bonne soirée,

Florent
